### ISSUE TITLE
liftover failed with cross map

### ISSUE THREAD

**Issue by udiland** [evotools/nf-LO#13]
Hi,
I have a failure in running the pipline, couldnt understand exactly why. 
Maybe it is looking for chain.null file?
Appreciate your help.
Thank you!

Here is the nextflow.log file (was to long to paste):  https://tauex-my.sharepoint.com/:u:/g/personal/udiland_tauex_tau_ac_il/EVrh6dGhb4BOieTEvjfMbo0BcKncSEU42bVw8KarMUbEHg?e=yKs6Nu

**Comment by RenzoTale88** [comment]
Hi
Thanks for using nf-LO!
Just paste the error log at the end please.
Thanks
Andrea
________________________________
From: udiland ***@***.***>
Sent: Wednesday, May 17, 2023 7:40:47 AM
To: evotools/nf-LO ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [evotools/nf-LO] liftover failed with cross map (Issue #13)


Hi,
I have a failure in running the pipline, couldnt understand exactly why.
Maybe it is looking for chain.null file?
Appreciate your help.
Thank you!

Here is the nextflow.log file (was to long to paste): https://tauex-my.sharepoint.com/:u:/g/personal/udiland_tauex_tau_ac_il/EVrh6dGhb4BOieTEvjfMbo0BcKncSEU42bVw8KarMUbEHg?e=yKs6Nu

**Comment by udiland** [comment]
Hello Andrea,
Thank you for your help.
Its looks like it fails in the crossmap stage.
Where can I find the error log you mention?
I see that the liftoff command looks not ok
This is what in the .command.sh file:
`CrossMap.py null liftover.chain long_chrUn_filtered.vcf liftover.null`
Thanks
Udi

**Comment by RenzoTale88** [comment]
Hi Udi,
Try specifying `--annotation_format vcf` and see if that works.
Andrea

**Comment by udiland** [comment]
Hi Andrea,

Thank you, it fix that issue, however I am getting another error.
The error is:
CrossMap.py: error: no such option: -a
When I look at the command it looks like this:
CrossMap.py vcf -a liftover.chain long_chrUn_filtered.vcf 190708.fasta liftover.vcf
I was able to produce the liftover vcf file by running the command without the -a option.

**Comment by RenzoTale88** [comment]
@udiland apologies for the late reply. This is a bug indeed. I'll work on a patch in the next days.

**Comment by RenzoTale88** [comment]
@udiland can you try the code now?
Be sure to clone the latest version:
```
git clone https://github.com/evotools/nf-LO
nextflow run ./nf-LO/ ...
```

Andrea

**Comment by udiland** [comment]
Hi Andrea,

I currently don't have the resources to run the analysis (I need to wait for others to finish their work).
I hope I will be able to check it soon.
Thank you for all the help.

Udi
