### ISSUE TITLE
minimap2: Stdin is empty 

### ISSUE THREAD

**Issue by vpeddu** [evotools/nf-LO#15]
Hi, 

I'm running nf-LO between hg38 and pantro6 using the minimap2 preset. The docker container used was built as suggested in the docs. I'm running this on a SLURM cluster launched via a login node. It looks like minimap2 fails but the `.exitcode` is still 0 so the downstream processes fail. I can confirm that the same files and settings work with lastz but not minimap2. 

I've also noticed that only one minimap2 process spawns whereas a few hundred lastz processes typically spawn. It seems that `splitsrc` and  `splittgt` each return a large single multifasta.

run script: 
```
nextflow run evotools/nf-LO \
	-latest \
	-c phoenix.config \
	--outdir pantro6_to_hg38_nflo \
	--distance near \
	--aligner minimap2 \
	--max_cpus 32 \
	--max_memory 128.GB \
	-w work3 \
	--source panTro6_cleaned.fa \
	--target hg38_cleaned.fa \
	-with-tower \
	-profile docker -with-docker vpeddu/nflo:latest
```

process `.command.error`: 
```
Got 30 lifts in source.lift
Lifting stdin
Got 328 lifts in target.lift
Lifting stdin
[M::mm_idx_gen::42.331*1.45] collected minimizers
[M::mm_idx_gen::68.360*2.79] sorted minimizers
[M::main::68.360*2.79] loaded/built the index for 30 target sequence(s)
[M::mm_mapopt_update::174.858*1.28] mid_occ = 121
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 30
[M::mm_idx_stat::259.800*0.94] distinct minimizers: 213075345 (92.73% are singletons); average occurrences: 1.328; average spacing: 10.079; total length: 2851453592
stdin is empty
```

**Comment by RenzoTale88** [comment]
Hi @vpeddu thanks for using `nf-LO`!

Yes, the minimap2 subworkflow is efficient enough to justify the use of a single job rather than splitting the sequence.
Do you mind:
1. sharing the content of `.command.sh`
2. pointing me to the two genomes

Thanks in advance 
Andrea

**Comment by vpeddu** [comment]
Hi Andrea, 

Thanks for the quick reply! The two genomes are hg38 and pantro6 from UCSC with their respective "chrUn" entries removed. 

I noticed that this workflow fails with the error described when I submit it as a job to a SLURM cluster, but succeeds when executed locally for some reason. Same command and files just different executor.

Here is the `.command.sh`
```
#!/bin/bash -ue
minimap2 -t 16 -cx asm5 --cs=long /private/groups/kimlab/vikas/liftover_tool/new_chains/pantro6_to_hg38/work3/f6/10045e6b3ebf84109fae4af0765a3b/SPLIT_src/src.fa /private/groups/kimlab/vikas/liftover_tool/new_chains/pantro6_to_hg38/work3/3c/69ba6297b8fcb7079fcc0239e268af/SPLIT_tgt/tgt.fa |
    paftools.js view -f maf - |
    maf-convert psl - |
    liftUp -type=.psl stdout source.lift warn stdin |
    liftUp -type=.psl -pslQ src.tgt.psl target.lift warn stdin
    ```

**Comment by RenzoTale88** [comment]
@vpeddu apologies for the many delays. I can confirm this bug when using the two genomes provided. I'll try to work on a patch in the next week or so.

**Comment by RenzoTale88** [comment]
@vpeddu I finally managed to apparently fix the issue. Do you mind trying the following:
1. clone the fixed branch of nf-LO
```
git clone -b mmap2_test https://github.com/evotools/nf-LO/
```
2. Try running the workflow as you've done so far. Add the option `--tgtSize 10000000` to have the workflow to combine small contigs in grouped alignment (it avoids creating too many small files)

The workflow should be able to complete successfully. The only difference is that it will fragment the target genome, allowing lower memory usage and, theorethically, fix the issue.

Please let me know if this sorts the problem out.

Andrea

**Comment by zy041225** [comment]
Hi Andrea @RenzoTale88 , 

I also met the same issue when lifting the clawed frog geome from Xenopus laevis genome v9.1 to v10.1. I have used your fixed branch and added the option `--tgtSize 10000000`. 

Similarly the `.command.sh` 

```
minimap2 -t 2 -cx asm5 --cs=long PATH/Xenopus_laevis.v9.1/nf-LO/work/85/611b3b306ad565fbf3686e8d9d6a67/SPLIT_src/src.fa PATH/Xenopus_laevis.v9.1/nf-LO/work/d2/523b738626b9349605eaa5d3982ee2/CLUST_tgt/tgt3.fa |
    paftools.js view -f maf - |
    maf-convert psl - |
    liftUp -type=.psl stdout source.lift warn stdin |
    liftUp -type=.psl -pslQ src.tgt3.psl target.lift warn stdin
```

Yang

**Comment by RenzoTale88** [comment]
@zy041225 thanks for letting me know about this. Just to be clear, do you come across the issue when using the fix above?

**Comment by zy041225** [comment]
yes, I clone the mmap2_test branch but still meet this issue.

**Comment by RenzoTale88** [comment]
Do you mind sharing the specifications of your system?

**Comment by RenzoTale88** [comment]
Are you running the workflow on a single machine (i.e. a laptop or desktop) or an cluster/HPC system? If on a single machine, how much memory does your machine have?

**Comment by zy041225** [comment]
It was run on a SLURM cluster.

**Comment by RenzoTale88** [comment]
Are you running it as an individual job, or with a specific cluster configuration? If the first, how much memory are you requesting?

**Comment by zy041225** [comment]
I put the command in a shell

```
#!/bin/bash
conda activate nf-LO
nextflow run /home/zhouyang/software/nf-LO --source PATH/Xenopus_laevis.v9.1/nf-LO/Xla.v91.repeatMasked.fa --target PATH/Xenopus_laevis.v9.1/nf-LO/genome.fa --outdir outDir -profile local --aligner minimap2 --distance near --tgtSize 10000000
```

and sbatch the job to the cluster requesting 20 CPU and 50 Gb memory

**Comment by RenzoTale88** [comment]
Ok, that gives me a bit more context. You can probably try to increase the process memory to 128G and check whether that succeed or not.

However, since you have access to a cluster, I would advise to check whether your system is among the supported from the [nf-core configurations]https://github.com/nf-core/configs/). If so, you can download the correct configuration file, and provide it using the `-c` option. That will easily speed up the workflow and avoid the memory issues, as nextflow provides the best performances when it can take advantage from the large distributed system, rather than run on an individual node.
I'd also recommend to discuss with your system admin before running it, as there might be additional tweaks to be done.

I'll try to run some tests in the next few days, and come up with some basic guidelines for single-node memory requirements.

**Comment by zy041225** [comment]
Thanks @RenzoTale88 , by setting the memory to 300 Gb the run succeeded.

**Comment by RenzoTale88** [comment]
@zy041225 apologies for the long delay with this. I've applied a few changes to the way the workflow runs the `minimap2` alignments to optimize speed and memory usage. If you wish, you can try v1.8.2, that carries these updated features.
