### ISSUE TITLE
Issue about Annotation 

### ISSUE THREAD

**Issue by GrazieT** [evotools/nf-LO#20]
Hi,
I met a problem about using nf-LO to liftover my genomes.
About Annotation param, If i support a gff file, this file is source genome's gff or target genome's gff?
Can you help me out?
Much appreciate.

**Comment by RenzoTale88** [comment]
@GrazieT the annotation refers to the source genome, and will be lifted to the target genome. 
Cheers
Andrea

**Comment by GrazieT** [comment]
Thanks a lot! I will Retry it.
