### ISSUE TITLE
chainnet file empty

### ISSUE THREAD

**Issue by MartinSchmitz95** [evotools/nf-LO#23]
Im running nf-lo for different genomes as follows:
`nextflow run evotools/nf-LO --source [source_fasta] --target  [target_fasta]  -with-singularity nflo.sif --aligner GSAlign --distance same --max_cpus 16 --outdir [my_out_dir]`

The command runs and gives no errors. Also for most genomes it succeeds and creates good chain files. However, when I try the Hi-C phased Ape genomes from UCSC [here](https://genome-asia.ucsc.edu/cgi-bin/hgGateway?hgsid=838766182_uroDOrvayTaLeZWBdwFyYxjnEE6M) the result is an empty chain file. More precisely I am trying to LiftOver: [Chimpanzee](https://genomeark.s3.amazonaws.com/species/Pan_troglodytes/mPanTro3/assembly_curated/mPanTro3_v2.0.2bit), first I seperate the reference into hap1 and hap2 and liftover between the two Haplotypes (The same problem exists for the two Urangutan and Siamang genomes from the same dataset too).
 I am wondering what could cause this issue.

**Comment by RenzoTale88** [comment]
Hi @MartinSchmitz95 thanks for using nf-LO! Do you mind sharing the log file for one of the failing analyses (file `.nextflow.log`). In the meanwhile, I'll try to reproduce the issue and figure out what is going on.

**Comment by MartinSchmitz95** [comment]
Hi @RenzoTale88 thank you so much for the fast answer. 
I cant find this logfile, do you know where it should be saved usually?

**Comment by MartinSchmitz95** [comment]
Alright here is the log file. I extracted chromosome 19 and try to liftover from chromosome 19 hap1 to chromosome 19 hap2 
[nextflow.log](https://github.com/user-attachments/files/16860094/nextflow.log)

**Comment by RenzoTale88** [comment]
@MartinSchmitz95 thanks for this. Can you also confirm which version of the workflow you are using?

**Comment by MartinSchmitz95** [comment]
Sure, I use: Nextflow LiftOver v 1.8.2

**Comment by RenzoTale88** [comment]
@MartinSchmitz95 thanks for notifying this, I found the issue. The problem lies in how we run `chainPreNet`, which normally excludes the files with naming `*_hap*` or `*_alt*`, unless the `-inclHap` option is provided. I apologise for the inconvenience, while I prepare a patch in the next few days, you can work around the issue by e.g. renaming the sequences e.g. `chr19_hap1_hsa19` to `chr19_h1_hsa19`.

Andrea

**Comment by MartinSchmitz95** [comment]
Hi @RenzoTale88, that is great news, I will rename them then. thank you so much!

**Comment by RenzoTale88** [comment]
@MartinSchmitz95 I'll leave this open until I make a patch to allow for haplotypes to be considered in the analysis, thanks for raising the issue :)

**Comment by MartinSchmitz95** [comment]
Okay sure, thank you :)

**Comment by RenzoTale88** [comment]
@MartinSchmitz95 Resolving as v1.8.3 adds support to haplotypes via the `--haplotypes` option.
Thanks for your feedback and let us know if you have any more trouble with the workflow.

Andrea
