### ISSUE TITLE
Process `ALIGNER:chainMerge (chainmerge)` terminated with an error exit status (1) -- Execution is retried (1)

### ISSUE THREAD

**Issue by zhoudreames** [evotools/nf-LO#3]
I got the error information when runing the n-Lo,this log showing in blow:

WARNING: Could not load nf-core/config profiles: https://raw.githubusercontent.com/nf-core/configs/master/nfcore_custom.config
Launching `https://github.com/evotools/nf-LO` [pedantic_ptolemy] DSL2 - revision: 312fb56810 [main]

======================================
          __           _      ____
         / _|         | |    / __ \
   _ __ | |_   ______ | |   | |  | |
  | '_ \|  _| |_____| | |   | |  | |
  | | | | |           | |___| |__| |
  |_| |_|_|           |______\____/
======================================
      Nextflow LiftOver v 1.6.0
======================================
source          : chrY.oldVersin.fa
target          : DRC.chrY.fa
aligner         : minimap2
distance        : medium
custom align    : -cx asm5 -l 10000
custom chain    : false
source chunk    : 20000000
source overlap  : 0
target chunk    : 10000000
target overlap  : 100000
output folder   : ./liftover_Minimap2
liftover name   : liftover
annot           : false
annot type      : false
liftover meth.  : liftover
igenomes_base   : s3://ngi-igenomes/igenomes/
igenomes_ignore : false
no_maf          : false
skip netsynt    : true
max cpu         : 143
max mem         : 26 GB
max rt          : 240.h
Using CrossMap
executor >  local (5)
[13/61a6e5] process > PREPROC:src2bit (src2Bit)   [100%] 1 of 1 ✔
executor >  local (10)
[13/61a6e5] process > PREPROC:src2bit (src2Bit)                  [100%] 1 of 1 ✔
[cb/e667b4] process > PREPROC:tgt2bit (tgt2Bit)                  [100%] 1 of 1 ✔
[3e/c206c5] process > PREPROC:splitsrc (splitsrc)                [100%] 1 of 1 ✔
[83/de485d] process > PREPROC:splittgt (splittgt)                [100%] 1 of 1 ✔
[73/c5a594] process > PREPROC:pairs (mkpairs)                    [100%] 1 of 1 ✔
[58/cefc2c] process > ALIGNER:minimap2 (minimap2.medium.src.tgt) [100%] 1 of 1 ✔
[26/7d4da4] process > ALIGNER:axtChain (axtchain_m)              [100%] 1 of 1 ✔
[33/4e27ca] process > ALIGNER:chainMerge (chainmerge)            [100%] 3 of 3, failed: 3, retries: 2 ✔
[-        ] process > ALIGNER:chainNet                           -
[-        ] process > ALIGNER:chainsubset                        -
[-        ] process > ALIGNER:chain2maf                          -
[-        ] process > ALIGNER:name_maf_seq                       -
[-        ] process > ALIGNER:mafstats                           -
[c7/cb6d2d] NOTE: Process `ALIGNER:chainMerge (chainmerge)` terminated with an error exit status (1) -- Execution is retried (1)
[8d/9085f1] NOTE: Process `ALIGNER:chainMerge (chainmerge)` terminated with an error exit status (1) -- Execution is retried (2)
[33/4e27ca] NOTE: Process `ALIGNER:chainMerge (chainmerge)` terminated with an error exit status (1) -- Error is ignored

**Comment by RenzoTale88** [comment]
@zhoudreames thank you for using nf-LO! I probably need a bit more information on how you run the workflow. Do you mind sharing the `.nextflow.log` file, so that I can have a bit more insight into it? Also, what type of configuration are you using?

Best
Andrea

**Comment by KristinaGagalova** [comment]
Hi
I am having the same issue with running the pipeline on local annotations. I am using the conda environment.
This is the error about chainMerger
```
NOTE: Process `ALIGNER:chainMerge (chainmerge)` terminated with an error exit status (1) -- Execution is retried (1)
Jun.-06 17:05:40.824 [Task submitter] INFO  nextflow.Session - [aa/ada0cd] Re-submitted process > ALIGNER:chainMerge (chainmerge)
Jun.-06 17:05:41.546 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 11; name: ALIGNER:chainMerge (chainmerge); status: COMPLETED; exit: 1; error: -; workDir: /my/work/dir
Jun.-06 17:05:41.547 [Task monitor] INFO  nextflow.processor.TaskProcessor - [aa/ada0cd] NOTE: Process `ALIGNER:chainMerge (chainmerge)` terminated with an error exit status (1) -- Execution is retried (2)
Jun.-06 17:05:41.554 [Task submitter] INFO  nextflow.Session - [a3/b6cb05] Re-submitted process > ALIGNER:chainMerge (chainmerge)
Jun.-06 17:05:42.229 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 12; name: ALIGNER:chainMerge (chainmerge); status: COMPLETED; exit: 1; error: -; workDir: /my/work/dir
```
Probably an error about mafstats installation?

**Comment by KristinaGagalova** [comment]
Thank you for the fast reply @RenzoTale88 

Here some more details:
1. I used the same identical command as the example on your tutorial - https://github.com/evotools/nf-LO#example (obviously switching with my local genomes). The genome size is of a few Mbp so I don't think there is any memory issue with that.
2. This is the error I have from that directory
```
mv: cannot stat 'run/000.chain': No such file or directory
```
so its probably chainMerge that doesn't produce the output. 
I hope this helps 

Thank you in advance
Kristina

**Comment by RenzoTale88** [comment]
@KristinaGagalova Thanks, this suggests me that some step before that probably failed for one reason or another. 
Could you please share with me both:
1. The content of the .command.sh file
2. The list of files in the current folder
3. Whether the input files for the `.command.sh` file contain anything.

In this way we can try to trace back where the issue originated.
Thanks!
Andrea

**Comment by KristinaGagalova** [comment]
1. ```.command.sh file```
```
#!/bin/bash -ue
chainMergeSort src16.tgt19.chain | chainSplit run stdin -lump=1 
mv run/000.chain ./rawchain.chain
```
2. List of file in ```work/a3/b6cb```
```
.command.begin  .command.err  .command.log  .command.out  .command.run  .command.sh  .command.trace  .exitcode  run  src16.tgt19.chain
```

3. This is the content of src16.tgt19.chain
```
##matrix=axtChain 16 91,-114,-31,-123,-114,100,-125,-31,-31,-125,100,-114,-123,-31,-114,91
##gapPenalties=axtChain O=400 E=30
```

**Comment by RenzoTale88** [comment]
Ok for whatever reason the chain file is effectively empty. The issue lies upstream from this. We can trace back the issue by looking at the folder in which `src16.tgt19.chain` is. You can trace it back by `ls -al work/a3/b6cb*/src16.tgt19.chain`. This should be a link to the file, specified after the `->` symbols. You can then enter that folder and check what went wrong there in the `.command.err` file.

**Comment by KristinaGagalova** [comment]
I don't get the same error on the test set so its probbaly something related to runs on local files
```
nextflow run evotools/nf-LO -profile test,conda
```

**Comment by RenzoTale88** [comment]
Is the file `src16.tgt19.psl` empty by any mean? I would proceed by looking at the single output, and if they're empty, trace backward by going to the linked folder as we've done for the previous file (i.e. `ls -al work/*/*/src16.tgt19.psl`, go the linked folder, check the input/output/err file).

**Comment by zhoudreames** [comment]
thanks for your help, I resolved it.

**Comment by zhoudreames** [comment]
tell me to close this problem if you solved it, thanks~

**Comment by RenzoTale88** [comment]
@zhoudreames thanks, I'll wait for @KristinaGagalova to confirm or rise more points on this. If it works for her I'll close it. Thanks again!

**Comment by KristinaGagalova** [comment]
@RenzoTale88 looks good now! Thank you for the fast fix

**Comment by JohnsonStev** [comment]
Hi, I am facing the same error with the latest version on the test commands
