### ISSUE TITLE
The current r-environment.yml never resolves

### ISSUE THREAD

**Issue by andersgs** [evotools/nf-LO#4]
Hello. 

Thank you for no-LO. 

I am running it with —annotation and —annotation_format. I am using the conda profile. 

It runs all the way to make_report, and then stalls while trying to create the conda environment.

I have tried to run conda env create directly to troubleshoot. Essentially, it gets stuck in the dependency solver section. By using the newer lmamba solver, it appears that some of the versions of the packages conflict. I am wondering if the versions could be relaxed or removed all together. 

Thanks again.

PS: It is the dependency hell problem. 😣

**Comment by RenzoTale88** [comment]
Hi @andersgs 
thank you for using nf-LO!

That is surprising to me, I've just tried to create the environment with mamba as well:
```
mamba env create -f environment.yml -p ${PWD}/nflo
```
And managed to install everything without issues.
Do you mind sharing the problem you are coming across? What platform are you testing the workflow in?

**Comment by andersgs** [comment]
Hi @RenzoTale88 

The behaviour for me was that Nextflow created one environment with the main environment file, and when I ran the workflow again but including —annotation it ran all the way up to making_report (I think that was the name - the last step where the HTML report is made), and then stalled while trying to create the environment in r-environment.yml. Internally, Nextflow is using conda env create.

I am running version 22.04.0 of Nextflow and the latest version of the workflow.

Sorry, when I said lmamba, I meant conda-libmamba-solver (https://github.com/conda-incubator/conda-libmamba-solver) which brings the mamba solver to conda. I am running conda version 4.13.

I am running everything on Ubuntu 22.04, on a machine with 16 CPUs and 128GB RAM.

I am wondering if there is something different in your conda config or perhaps with the r-environment.yml. Perhaps something with how you have your channels setup? Or maybe the Python version? My environment is running 3.9.

I created a separate environment with mamba, and with that I was able to get the environment created. 

Perhaps you could add the useMamba parameter to the conda profile, or maybe create a mamba profile where the conda config has useMamba=true? That would give the users the opportunity to use Mamba if they wish.

Thank you again.

**Comment by RenzoTale88** [comment]
Hi @andersgs 
Thanks for this, I've found the issue behind the problem. I forgot to update the conda configuration to use the default environment, which should be able to run the last stage regardless. I've pushed a fix to this, so if you can try to run:
```
nextflow drop evotools/nf-LO
```

And then rerun the workflow it should fix the issue.

In addition, I'll try to support mamba in the workflow using a specific flag. However, before pushing this functionality I need to perform a few tests beforehand. Once available, I'll update the documentation to specify this.

Thanks for this!
Andrea

**Comment by andersgs** [comment]
Thank you @RenzoTale88. I will give it a go. 

I am not sure it will work though. The environment.yml file in the assets folder does not have any of the R dependencies listed. However, the one in the base dir does. 

Is that correct?

**Comment by RenzoTale88** [comment]
@andersgs you are right. Please hold back and give me a few hours to find a solution to the issue.
Apologies for this.
Andrea

**Comment by andersgs** [comment]
Using the --mamba flag works. Thank you @RenzoTale88
