### ISSUE TITLE
Minimap2 and gsalign using too few cpus

### ISSUE THREAD

**Issue by andersgs** [evotools/nf-LO#5]
Hello @RenzoTale88. 

My machine has 16 CPUs, and by default no-LO sets the max to 15 cpus. I think that is reasonable. 

But, I noticed that both minimap2 and gsalign, which share the cpus definition in the config files, end up with only 7 cpus while running. Is there a particular reason for halving the cpus for these two tools? 

I noticed that the function check_max returns the minimum of max cpus / 2 * the number of tries and the max number of cpus. So, it will always return at most half the number of max cpus. Is that the intended behaviour?

Thanks again.

**Comment by RenzoTale88** [comment]
Hello @andersgs 
The definition of the resources is always a bit of a tricky thing, especially for local machines where it is easy to cause crashes and similar. 
When I put together nf-LO, I made the consideration that running on a local machine might involve running the workflow while other tools would be running in the background. To minimize the disruption, I set the resources to use at most half of the cores initially, and then progressively increase in number at each failure until hitting the maximum cpus available.
The code you are referring is this one:
```
  withLabel: gsalign{
    cpus = { check_max(params.max_cpus / 2 * task.attempt, 'cpus') }
    memory = { check_max( 8.GB * task.attempt, 'memory' ) }
    time = { check_max( 12.h * task.attempt, 'time' ) }
  }
```
This will first compute the number of cores as you said (`params.max_cpus / 2 * task.attempt`), and only then limit it ot the maximum number of cores available.
In a nutshel, considering a maximum number of cores that you specified, nf-LO will proceed as follow:
1. Attempt 1: use max_cpus/2*nattempts = 15/2*1 = 7
2. Attempt 2: 15/2*2 = 14
3. Attempt 3: 15/2*3 = 22, but here the check_max kicks in and limits it to 15

Hope this clarifies your doubt. It is tricky to optimize the resources for each use-case, but if you prefer you can copy and edit the configuration file locally, and then specify it using the flags `--my_config configuration.conf -profile custom_profile`.

Let me know if this help
Best
Andrea

**Comment by andersgs** [comment]
Thank you for the responde @RenzoTale88. Your explanation makes sense. In my head, I would've expected the opposite approach. In other words, start with as many CPUs as possible, and decrease with the number of tries. But, I see how your approach is more cautionary.
