### ISSUE TITLE
pipeline commands

### ISSUE THREAD

**Issue by marcovth** [evotools/nf-LO#6]
Is there an option for nf-LO to simply generate the pipeline commands into a text file, so that I can run every step one-by-one.

nf-LO Keeps randomly crashing, is has been a highly frustrating experience.

**Comment by RenzoTale88** [comment]
@marcovth I don't think it is a functionality contemplated by nextflow. However, you can extrapolate the commands you need from the many `.nf` files [here](https://github.com/evotools/nf-LO/tree/main/modules/processes).
I'm sorry to hear you're having issues with running nf-LO. If you want to share the problems and use-case with us in a separate GitHub issue I will happily try to find out what is not working.
