### ISSUE TITLE
How to merge chain file from different chromosome 

### ISSUE THREAD

**Issue by zhoudreames** [evotools/nf-LO#9]
I split the genome into 20 chromosomes and then ran nf-Lo with blat alignments for each chromosome.  I don't know how to merge all chain files into one chain, can you help me ?

**Comment by RenzoTale88** [comment]
@zhoudreames thank you for using nf-LO!
My suggestion is to run nf-LO on the whole genome at once and leave nf-LO to combine the data itself. nf-LO split the genome in fragments of different sizes and then combine.

Having said that, if you want to proceed with the individual chains you can combine the files using chainMergeSort and chainSplit in sequence:
```
chainMergeSort *.chains | chainSplit run stdin -lump=1 
mv run/000.chain ./merged.chain
```
Then generate the net file:
```
chainPreNet merged.chain source.sizes target.sizes stdout |
        chainNet -verbose=0 stdin source.sizes target.sizes netfile.net /dev/null 
```
And finally create the resulting liftover:
```
netChainSubset -verbose=0 netfile.net merged.chain stdout | chainStitchId stdin stdout > liftover.chain
```

Hope this helps

Andrea
